-- Tâches converties depuis les 59 checklists "Feuille de route" fournies par
-- Jordan (il s'agissait en réalité de tâches, pas de checklists
-- standalone — voir 0021_remove_standalone_checklists.sql). Le titre de la
-- checklist devient la catégorie ; priorité par défaut (normale), pas
-- d'échéance ni de responsable assignés.

insert into _20260725_tasks (title, category, status) values
  ('Alimenter le tableau de suivi des dépenses avec toutes les dépenses engagées à ce jour', 'Avant — Budget & administratif', 'todo'),
  ('Créer l’échéancier des paiements restants par prestataire avec dates limites', 'Avant — Budget & administratif', 'todo'),
  ('Effectuer les paiements aux dates prévues et conserver tous les justificatifs', 'Avant — Budget & administratif', 'todo'),
  ('Préparer les enveloppes de paiement espèces pour le jour J si nécessaire', 'Avant — Budget & administratif', 'todo'),
  ('Vérifier les conditions d’annulation dans chaque contrat', 'Avant — Budget & administratif', 'todo'),
  ('Définir et réserver l’enveloppe imprévus (5–10 % du budget total)', 'Avant — Budget & administratif', 'todo'),
  ('Centraliser tous les contrats dans un dossier unique numérique', 'Avant — Budget & administratif', 'todo'),
  ('Vérifier les plafonds bancaires et contacter la banque si des virements importants sont prévus', 'Avant — Budget & administratif', 'todo'),
  ('Envoyer le déroulé minuté au Grand Arbre', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Demander si l’accès est possible la veille pour décoration et dépôt des boissons', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Communiquer le nombre définitif d’invités au Grand Arbre', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Confirmer le nombre exact de tables disponibles', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Planifier la visite technique avec le DJ — premier week-end de juillet', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Établir le plan de salle par zones : accueil, cocktail, dîner, danse, enfants', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Valider le menu définitif avec le traiteur du lieu', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Valider le timing de service : cocktail, plat, dessert, café', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Confirmer exactement ce qui est inclus dans la prestation nettoyage, notamment les poubelles', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Clarifier la procédure d’état des lieux de sortie avec le propriétaire', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Préparer la signalétique de bienvenue et le fléchage depuis le parking', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Faire la visite technique avec le DJ — premier week-end de juillet', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Tester sur place que la sono de Djahman couvre bien l’espace extérieur du Grand Arbre', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Simuler le parcours du cortège et vérifier que le son porte jusqu’au fond', 'Avant — Lieu / Grand Arbre', 'todo'),
  ('Commander les spécialités malgaches : prestataire, quantités, date de livraison', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Formaliser la recette des spécialités indiennes', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Définir les quantités des spécialités indiennes', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Acheter les épices pour les spécialités indiennes', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Couper les ingrédients : ail, tomates, oignons, cressons', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Commander les bonbons piments', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Valider avec Christiana qu’on peut préparer les mini bokits à la maison', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Acheter les ingrédients des spécialités guadeloupéennes', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Proposer 3 garnitures : jambon halal/fromage, poulet, thon', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Acheter une grande marmite adaptée à la friture en grande quantité, environ 40 cm', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Prévoir 30 cartons alimentaires adaptés au transport des fritures et spécialités fragiles', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Planifier qui prépare quoi, où et quand : veille ou matin du jour J', 'Avant — Traiteurs externes & spécialités', 'todo'),
  ('Maintenir le fichier Excel du stock local à jour avec les quantités exactes', 'Avant — Boissons', 'todo'),
  ('Louer un utilitaire pour le transport des boissons la veille', 'Avant — Boissons', 'todo'),
  ('Recruter des cousins pour aider au chargement à la maison et au déchargement à la salle', 'Avant — Boissons', 'todo'),
  ('Louer ou acheter le matériel bar pour la période 1h–4h : glacières, bacs à glaçons, seaux, pinces', 'Avant — Boissons', 'todo'),
  ('Calculer la quantité de glace nécessaire pour tenir jusqu’à 4h en plein été', 'Avant — Boissons', 'todo'),
  ('Désigner le responsable boissons jour J', 'Avant — Boissons', 'todo'),
  ('Lister tout le matériel à louer : jeux de lumières, glacières supplémentaires, panneaux de signalétique, mobilier éventuel', 'Avant — Location de matériel', 'todo'),
  ('Confirmer avec Djahman ce qu’il apporte en éclairage et ce qui reste à prévoir', 'Avant — Location de matériel', 'todo'),
  ('Demander des devis pour la location du matériel lumière manquant', 'Avant — Location de matériel', 'todo'),
  ('Réserver le matériel auprès d’un loueur', 'Avant — Location de matériel', 'todo'),
  ('Arbitrer acheter vs louer pour chaque élément : glacières, panneaux, etc.', 'Avant — Location de matériel', 'todo'),
  ('Envoyer un message à tous les participants confirmés : remerciements + choix du plat poulet ou poisson', 'Avant — RSVP', 'todo'),
  ('Relancer les retardataires n’ayant pas encore répondu', 'Avant — RSVP', 'todo'),
  ('Recueillir les horaires d’arrivée de chaque invité : vol, train, voiture', 'Avant — RSVP', 'todo'),
  ('Compiler le tableau final : nom, présence, plat, horaire d’arrivée, besoins transport', 'Avant — RSVP', 'todo'),
  ('Communiquer les chiffres définitifs au Grand Arbre : traiteur + salle', 'Avant — RSVP', 'todo'),
  ('Hôtels identifiés, codes promo obtenus et guide invités envoyé', 'Avant — Hébergement invités', 'done'),
  ('Vérifier que tous les invités venant de loin ont bien reçu le guide hébergement', 'Avant — Hébergement invités', 'todo'),
  ('Demander qui loge où', 'Avant — Hébergement invités', 'todo'),
  ('Cartographier les besoins en transport le jour J à partir des horaires d’arrivée collectés', 'Avant — Transport invités', 'todo'),
  ('Identifier les invités sans moyen de retour tard dans la nuit et prévoir un VTC/taxi', 'Avant — Transport invités', 'todo'),
  ('Communiquer les modalités de transport à tous les invités concernés', 'Avant — Transport invités', 'todo'),
  ('Noter le contact VTC/taxi de nuit à avoir sous la main le jour J', 'Avant — Transport invités', 'todo'),
  ('Mail de brief envoyé à Djahman le 22 juin', 'Avant — DJ / Djahman', 'done'),
  ('S’assurer que Djahman a bien répondu au Google Forms', 'Avant — DJ / Djahman', 'todo'),
  ('Obtenir confirmation du matériel : sono mobile extérieur, sono salle, diffusion terrasse, micros sans fil', 'Avant — DJ / Djahman', 'todo'),
  ('Confirmer que le matériel est adapté à environ 90 personnes', 'Avant — DJ / Djahman', 'todo'),
  ('Obtenir ses besoins en alimentation électrique pour anticiper avec le lieu', 'Avant — DJ / Djahman', 'todo'),
  ('Confirmer son heure d’arrivée souhaitée et le temps nécessaire à l’installation', 'Avant — DJ / Djahman', 'todo'),
  ('Obtenir ses recommandations pour l’éclairage de la soirée dansante', 'Avant — DJ / Djahman', 'todo'),
  ('Planifier sa venue pour la visite technique début juillet', 'Avant — DJ / Djahman', 'todo'),
  ('Valider la version extended 30 min du morceau d’entrée du cortège', 'Avant — DJ / Djahman', 'todo'),
  ('Confirmer “A love song” – Garth Stevenson pour l’arrivée de Sarah', 'Avant — DJ / Djahman', 'todo'),
  ('Confirmer “Se pas pou dat” – Zo konpa / Konpa Lakay pour la présentation de la bague', 'Avant — DJ / Djahman', 'todo'),
  ('Définir ensemble les musiques du cocktail et du repas', 'Avant — DJ / Djahman', 'todo'),
  ('Convenir du canal de communication discret le jour J : intermédiaire ou SMS', 'Avant — DJ / Djahman', 'todo'),
  ('Référentiel Excel + Spotify transmis', 'Avant — Playlist', 'done'),
  ('S’assurer que Djahman a bien ouvert le fichier Excel référentiel', 'Avant — Playlist', 'todo'),
  ('Lui transmettre les morceaux disponibles sur YouTube uniquement, hors Spotify', 'Avant — Playlist', 'todo'),
  ('Valider avec lui la structure de la soirée dansante : blocs, transitions, montée progressive', 'Avant — Playlist', 'todo'),
  ('Confirmer les morceaux “priorité à notre sélection” : Seggae, Salegy malgache, Bollywood, Pop indienne, Arabic', 'Avant — Playlist', 'todo'),
  ('Contrat signé et acompte versé', 'Avant — Photographe / Vidéaste', 'done'),
  ('Créer le groupe WhatsApp avec les deux numéros + 07 84 96 72 89', 'Avant — Photographe / Vidéaste', 'todo'),
  ('Partager le déroulé de la journée dans le groupe dès qu’il est finalisé', 'Avant — Photographe / Vidéaste', 'todo'),
  ('Rassembler des inspirations photo/vidéo : style, ambiance, cadrage', 'Avant — Photographe / Vidéaste', 'todo'),
  ('Rédiger la shot list : photos indispensables, familles, moments clés, portraits officiels', 'Avant — Photographe / Vidéaste', 'todo'),
  ('Confirmer l’heure d’arrivée souhaitée avant les invités pour salle vide + préparatifs', 'Avant — Photographe / Vidéaste', 'todo'),
  ('Prévenir les familles en amont de limiter les téléphones pendant la cérémonie', 'Avant — Photographe / Vidéaste', 'todo'),
  ('Définir le thème visuel et la palette de couleurs', 'Avant — Décoration', 'todo'),
  ('Lister les éléments déco par zone : entrée, cortège, table d’honneur, tables invités, espace danse', 'Avant — Décoration', 'todo'),
  ('Contacter et choisir un fleuriste', 'Avant — Décoration', 'todo'),
  ('Valider les compositions florales et les tarifs', 'Avant — Décoration', 'todo'),
  ('Comparer achat, location et DIY pour chaque élément puis arbitrer', 'Avant — Décoration', 'todo'),
  ('Créer le plan de décoration par zone avec photos de référence', 'Avant — Décoration', 'todo'),
  ('Commander ou acquérir tous les éléments déco avec délais de livraison compatibles', 'Avant — Décoration', 'todo'),
  ('Confirmer la livraison des fleurs : heure, lieu, référent sur place', 'Avant — Décoration', 'todo'),
  ('Vêtement reçu', 'Avant — Tenue Sarah', 'done'),
  ('Trouver et commander les chaussures assorties', 'Avant — Tenue Sarah', 'todo'),
  ('Trouver et commander les bijoux assortis', 'Avant — Tenue Sarah', 'todo'),
  ('Organiser un essayage complet tenue + chaussures', 'Avant — Tenue Sarah', 'todo'),
  ('Laver et repasser le lehenga dans un pressing', 'Avant — Tenue Sarah', 'todo'),
  ('Choisir le style de coiffure', 'Avant — Tenue Sarah', 'todo'),
  ('Trouver la coiffeuse', 'Avant — Tenue Sarah', 'todo'),
  ('Faire un essai coiffure', 'Avant — Tenue Sarah', 'todo'),
  ('Réserver la coiffeuse pour le jour J', 'Avant — Tenue Sarah', 'todo'),
  ('Réaliser un essai maquillage', 'Avant — Tenue Sarah', 'todo'),
  ('Prendre le rendez-vous de maquillage pour le jour J', 'Avant — Tenue Sarah', 'todo'),
  ('Trouver des faux ongles', 'Avant — Tenue Sarah', 'todo'),
  ('Identifier et commander la tenue définitive avec délai de livraison confirmé', 'Avant — Tenue Jordan', 'todo'),
  ('Prévoir les retouches si nécessaire', 'Avant — Tenue Jordan', 'todo'),
  ('Trouver et commander les chaussures assorties', 'Avant — Tenue Jordan', 'todo'),
  ('Choisir les accessoires : pochette, montre, etc.', 'Avant — Tenue Jordan', 'todo'),
  ('Faire un essayage complet tenue + chaussures avant le jour J', 'Avant — Tenue Jordan', 'todo'),
  ('RDV coiffure pris le 25/07 à 10h', 'Avant — Tenue Jordan', 'done'),
  ('Vérifier si le rendez-vous coiffure existant doit être maintenu, décalé ou confirmé', 'Avant — Tenue Jordan', 'todo'),
  ('Désigner un MC / coordinateur discours pour les transitions', 'Avant — Discours', 'todo'),
  ('Prévoir un micro-test avec les parents', 'Avant — Discours', 'todo'),
  ('Rédiger le conducteur minuté complet : accueil, cortège, cérémonie, cocktail, dîner, soirée, remerciements, fin', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Valider le conducteur avec tous les prestataires clés : DJ, traiteur, photographe', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Faire le point avec les parents de Sarah sur leurs interventions pendant la cérémonie', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Identifier les temps morts et prévoir des animations ou transitions', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Gérer la chaleur pour les invités pendant la cérémonie extérieure : ombre, eau fraîche, éventails', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Faire le point avec les parents de Jordan sur leurs interventions pendant la cérémonie', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Désigner un maître de cérémonie / coordinateur de soirée : Lisa', 'Avant — Déroulé de la cérémonie', 'done'),
  ('Prévoir un plan B pour chaque moment critique : météo, retard prestataire, son défaillant', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Imprimer le conducteur en plusieurs exemplaires pour le jour J', 'Avant — Déroulé de la cérémonie', 'todo'),
  ('Récupérer auprès du Grand Arbre le nombre exact de tables et leur capacité', 'Avant — Plan de table', 'todo'),
  ('Créer les marque-places pour le plat et les numéros de table', 'Avant — Plan de table', 'todo'),
  ('Imprimer le plan de table pour affichage à l’entrée de la salle', 'Avant — Plan de table', 'todo'),
  ('Réaliser un premier plan de table et le valider avec Sarah', 'Avant — Plan de table', 'todo'),
  ('Intégrer les contraintes : mobilité réduite, personnes âgées, enfants, affinités / tensions', 'Avant — Plan de table', 'todo'),
  ('Données collectées via RSVP', 'Avant — Restrictions alimentaires', 'done'),
  ('Définir le système d’identification à table : marque-place codé, étiquette discrète, etc.', 'Avant — Restrictions alimentaires', 'todo'),
  ('Signaler les allergies sévères à l’ensemble de l’équipe de service', 'Avant — Restrictions alimentaires', 'todo'),
  ('Préparer la signalétique pour les plats des buffets et amuse-bouches : allergènes, halal, végé, etc.', 'Avant — Restrictions alimentaires', 'todo'),
  ('Décider si un cadeau ou une attention est prévu pour les parents', 'Avant — Cadeaux parents', 'todo'),
  ('Choisir le type de cadeau, commander avec délai compatible et organiser la distribution le jour J', 'Avant — Cadeaux parents', 'todo'),
  ('Save the date et invitations envoyés', 'Avant — Communication aux invités', 'done'),
  ('Envoyer un message individuel ou par famille : remerciement RSVP + choix poulet/poisson + horaire d’arrivée attendu', 'Avant — Communication aux invités', 'todo'),
  ('Envoyer un rappel général J-7 avec programme, accès, parking, dress code, météo anticipée', 'Avant — Communication aux invités', 'todo'),
  ('Rédiger le message de remerciement post-événement à l’avance', 'Avant — Communication aux invités', 'todo'),
  ('Lister tous les prestataires professionnels et amis avec rôle, contact et horaire d’intervention', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Avoir un numéro de contact de secours pour chaque prestataire clé', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Créer un document de coordination partagé accessible à tous les référents', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent logistique boissons', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent décoration', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent spécialités culinaires', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent fleurs', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le coordinateur général', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner les référents accueil invités', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent enfants', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent personnes âgées', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent cortège', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent discours / MC', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent enveloppes & cadeaux', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent parking', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent boissons', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent imprévus', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner le référent logistique rangement', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Contacter chaque référent pour confirmer son accord, son périmètre et lui fournir une boîte à outils', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Organiser une réunion de coordination 1–2 semaines avant, idéalement lors de la visite technique', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Désigner un interlocuteur unique sur place pour tous les prestataires', 'Avant — Coordination prestataires et référents', 'todo'),
  ('Définir la composition et l’ordre du cortège', 'Avant — Gestion du cortège', 'todo'),
  ('Prévenir chaque personne du cortège de son rôle et de ce qu’elle devra faire', 'Avant — Gestion du cortège', 'todo'),
  ('Choisir et synchroniser les musiques d’entrée avec Djahman', 'Avant — Gestion du cortège', 'todo'),
  ('Prévoir les alternatives pour les personnes à mobilité réduite', 'Avant — Gestion du cortège', 'todo'),
  ('Trouver un plateau de présentation et l’orner', 'Avant — Gestion du cortège', 'todo'),
  ('Découper la répétition de la cérémonie en séquences à répéter', 'Avant — Répétition de la cérémonie', 'todo'),
  ('Organiser la répétition avec les personnes clés du cortège et de la cérémonie', 'Avant — Répétition de la cérémonie', 'todo'),
  ('Recenser le nombre d’enfants présents et leurs âges', 'Avant — Gestion des enfants', 'todo'),
  ('Prévoir le contenu de l’espace enfants : jeux, coloriages, tapis', 'Avant — Gestion des enfants', 'todo'),
  ('Confirmer avec le traiteur le menu enfants et les horaires adaptés', 'Avant — Gestion des enfants', 'todo'),
  ('Identifier les personnes âgées ou à mobilité réduite dans la liste des invités', 'Avant — Gestion des personnes âgées', 'todo'),
  ('Prévoir leur placement à une table accessible : proche sortie, sanitaires, sans marche', 'Avant — Gestion des personnes âgées', 'todo'),
  ('Anticiper leur départ anticipé et prévoir un transport si nécessaire', 'Avant — Gestion des personnes âgées', 'todo'),
  ('Choisir et préparer l’urne ou boîte sécurisée', 'Avant — Gestion des enveloppes', 'todo'),
  ('Désigner une personne de confiance pour gérer l’urne toute la soirée', 'Avant — Gestion des enveloppes', 'todo'),
  ('Établir la liste de colisage : ce qui part de la maison, ce qui vient du local, ce qui repart où', 'Avant — Rangement', 'todo'),
  ('Désigner l’équipe de rangement post-soirée, distincte de l’équipe installation', 'Avant — Rangement', 'todo'),
  ('Constituer la boîte à urgences : ruban adhésif, épingles, médicaments de base, chargeur, monnaie, anti-moustiques', 'Avant — Boîte à urgences', 'todo'),
  ('Préparer le kit couture / tenue de rechange pour incidents vestimentaires', 'Avant — Boîte à urgences', 'todo'),
  ('Compiler la liste des contacts d’urgence : prestataires, propriétaire du lieu, médecin', 'Avant — Boîte à urgences', 'todo'),
  ('Valider l’installation déco avant de partir', 'Installation — Fiancés / coordination générale', 'todo'),
  ('Faire le tour de contrôle final de la salle', 'Installation — Fiancés / coordination générale', 'todo'),
  ('Rappeler aux intervenants des discours leur ordre de passage et leur durée', 'Installation — Fiancés / coordination générale', 'todo'),
  ('S’assurer que tous les référents ont reçu le conducteur imprimé', 'Installation — Fiancés / coordination générale', 'todo'),
  ('Préparer les tenues respectives pour le lendemain : rangées, accessoires prêts', 'Installation — Fiancés / coordination générale', 'todo'),
  ('Confirmer les horaires de chacun pour le lendemain matin', 'Installation — Fiancés / coordination générale', 'todo'),
  ('Récupérer l’utilitaire loué tôt le matin', 'Installation — Logistique boissons', 'todo'),
  ('Organiser le chargement depuis le local avec les cousins mobilisés', 'Installation — Logistique boissons', 'todo'),
  ('Acheminer les boissons au Grand Arbre', 'Installation — Logistique boissons', 'todo'),
  ('Superviser le déchargement et le rangement dans l’espace prévu', 'Installation — Logistique boissons', 'todo'),
  ('Organiser la mise au froid : champagne, despé, jus, coca dans les glacières ou frigo du lieu', 'Installation — Logistique boissons', 'todo'),
  ('Ranger et sécuriser le matériel bar de relais : glacières supplémentaires, seaux, pinces', 'Installation — Logistique boissons', 'todo'),
  ('Vérifier les quantités à l’arrivée par rapport au fichier Excel de stock', 'Installation — Logistique boissons', 'todo'),
  ('Installer les éléments structurants en premier : backdrop, arches, nappes', 'Installation — Décoration', 'todo'),
  ('Disposer la décoration de table : centres de table, marque-places, bougies, numéros', 'Installation — Décoration', 'todo'),
  ('Installer la signalétique : plan de table à l’entrée, panneau bienvenue, numéros de table', 'Installation — Décoration', 'todo'),
  ('Tester et ajuster l’éclairage décoratif', 'Installation — Décoration', 'todo'),
  ('Réceptionner les compositions florales du fleuriste', 'Installation — Décoration', 'todo'),
  ('Vérifier que les compositions sont conformes à la commande', 'Installation — Décoration', 'todo'),
  ('Mettre de l’eau dans les vases si livraison anticipée', 'Installation — Décoration', 'todo'),
  ('Photographier la salle terminée et envoyer aux fiancés pour validation', 'Installation — Décoration', 'todo'),
  ('Réceptionner les spécialités malgaches et indiennes commandées et vérifier leur conformité', 'Installation — Spécialités culinaires', 'todo'),
  ('Superviser la préparation des spécialités guadeloupéennes à la maison', 'Installation — Spécialités culinaires', 'todo'),
  ('Préparer les fritures en grande quantité avec la marmite dédiée', 'Installation — Spécialités culinaires', 'todo'),
  ('Conditionner toutes les spécialités dans les boîtes de transport adaptées', 'Installation — Spécialités culinaires', 'todo'),
  ('S’assurer que tout est prêt et conditionné pour le lendemain matin', 'Installation — Spécialités culinaires', 'todo'),
  ('Ranger les spécialités dans un endroit frais et sécurisé jusqu’au transport le jour J', 'Installation — Spécialités culinaires', 'todo'),
  ('Confirmer les horaires d’arrivée de chacun le lendemain avec tous les référents', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Confirmer avec le Grand Arbre l’accès pour le lendemain : heure d’ouverture, point d’entrée', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Confirmer l’heure d’arrivée du DJ à 16h30 et du photographe/vidéaste', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Imprimer et distribuer le conducteur à tous les référents', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Vérifier que les enveloppes de paiement espèces jour J sont prêtes', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Rappeler aux intervenants des discours leur ordre de passage et leur durée', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Préparer la boîte à urgences si ce n’est pas déjà fait', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Organiser le stockage des boissons au Grand Arbre selon le planning de refroidissement', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Vérifier que le champagne est bien au froid pour le lendemain dès 17h', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Calculer et commander la glace nécessaire si livraison possible la veille', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Confirmer que le plan de décoration par zone avec photos de référence est imprimé ou accessible', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Vérifier que les marque-places et numéros de table sont prêts', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Préparer les panneaux de signalétique parking', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Faire le tour de contrôle de la salle : déco, boissons au froid, mobilier en place', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Vérifier que les bonbons piments réunionnais sont réceptionnés et conditionnés', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Vérifier que l’urne enveloppes est prête et placée à son emplacement', 'Installation — Tâches génériques de la veille', 'todo'),
  ('S’assurer que rien ne manque en comparant à la liste de colisage', 'Installation — Tâches génériques de la veille', 'todo'),
  ('Être prêts : tenue, coiffure, maquillage avant 17h00', 'Évènement — Fiancés', 'todo'),
  ('Donner le signal de départ du conducteur au coordinateur général', 'Évènement — Fiancés', 'todo'),
  ('Accueillir le DJ à 16h30, lui montrer l’espace, vérifier branchements et soundcheck', 'Évènement — Coordinateur général / avant ouverture', 'todo'),
  ('S’assurer que le DJ dispose d’eau et d’un espace de pause', 'Évènement — Coordinateur général / avant ouverture', 'todo'),
  ('Accueillir le photographe/vidéaste, lui remettre la shot list et le conducteur', 'Évènement — Coordinateur général / avant ouverture', 'todo'),
  ('Présenter au photographe/vidéaste les personnes clés dès que possible', 'Évènement — Coordinateur général / avant ouverture', 'todo'),
  ('Faire le tour de contrôle final de la salle avant l’arrivée des invités', 'Évènement — Coordinateur général / avant ouverture', 'todo'),
  ('Vérifier que le micro est opérationnel', 'Évènement — Coordinateur général / avant ouverture', 'todo'),
  ('Synchroniser les montres ou téléphones avec le DJ et le photographe', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Superviser le positionnement des placeurs pour l’accueil des invités', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Donner le signal de départ du cortège à 17h30', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Suivre le conducteur minute par minute pendant toute la cérémonie', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Communiquer avec le DJ via signal discret', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Alerter discrètement si un retard se creuse', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Superviser la transition cérémonie → cocktail → salle de réception', 'Évènement — Coordinateur général / cérémonie', 'todo'),
  ('Confirmer l’heure de début du service avec le responsable traiteur', 'Évènement — Coordinateur général / dîner et soirée', 'todo'),
  ('Surveiller le timing entre les plats pour rester dans le conducteur', 'Évènement — Coordinateur général / dîner et soirée', 'todo'),
  ('Signaler au traiteur tout changement de programme', 'Évènement — Coordinateur général / dîner et soirée', 'todo'),
  ('Signaler au DJ les transitions importantes : premier slow, montée dancefloor, clôture', 'Évènement — Coordinateur général / dîner et soirée', 'todo'),
  ('Valider avec le traiteur les horaires du dessert à 23h00, du café et du départ de l’équipe', 'Évènement — Coordinateur général / dîner et soirée', 'todo'),
  ('Confirmer l’heure de fin de prestation du DJ et la musique de clôture', 'Évènement — Coordinateur général / dîner et soirée', 'todo'),
  ('Poser la signalétique directionnelle depuis l’accès principal', 'Évènement — Parking', 'todo'),
  ('Bloquer ou signaler l’espace fond de parking réservé aux fiancés', 'Évènement — Parking', 'todo'),
  ('Orienter chaque voiture vers l’entrée du parking', 'Évènement — Parking', 'todo'),
  ('Avoir le contact du propriétaire du lieu pour toute voiture à déplacer si nécessaire', 'Évènement — Parking', 'todo'),
  ('Informer le coordinateur général quand les arrivées se stabilisent vers 18h15', 'Évènement — Parking', 'todo'),
  ('Vérifier que la signalétique d’accueil est en place : plan de table affiché, fléchage terrasse', 'Évènement — Accueil invités', 'todo'),
  ('Pointer les arrivées sur la liste de présence', 'Évènement — Accueil invités', 'todo'),
  ('Orienter chaque invité vers la terrasse cocktail', 'Évènement — Accueil invités', 'todo'),
  ('S’assurer que les boissons d’accueil sont disponibles dès 17h00', 'Évènement — Accueil invités', 'todo'),
  ('Gérer les arrivées tardives avec discrétion pendant la cérémonie', 'Évènement — Accueil invités', 'todo'),
  ('Rassembler les membres du cortège à 17h20', 'Évènement — Cortège', 'todo'),
  ('Vérifier que chacun connaît sa place et son rôle', 'Évènement — Cortège', 'todo'),
  ('Coordonner avec le DJ le signal de lancement de la musique d’entrée', 'Évènement — Cortège', 'todo'),
  ('Donner le signal de départ au premier rang du cortège', 'Évènement — Cortège', 'todo'),
  ('Briefer le photographe sur le déroulé du cortège juste avant', 'Évènement — Cortège', 'todo'),
  ('Tester le micro et le retour son avant le premier discours', 'Évènement — Discours / MC', 'todo'),
  ('Coordonner avec le DJ la musique de fond éventuelle', 'Évènement — Discours / MC', 'todo'),
  ('Annoncer et remercier chaque intervenant avec fluidité', 'Évènement — Discours / MC', 'todo'),
  ('Gérer le timing discrètement si un orateur dépasse', 'Évènement — Discours / MC', 'todo'),
  ('S’assurer que chaque orateur a son texte sur papier ou téléphone chargé', 'Évènement — Discours / MC', 'todo'),
  ('Vérifier à l’ouverture que les boissons d’accueil sont en place et au froid', 'Évènement — Boissons', 'todo'),
  ('Superviser le service des boissons pendant le cocktail', 'Évènement — Boissons', 'todo'),
  ('S’assurer que les tables sont régulièrement resservies en eau et boissons pendant le dîner', 'Évènement — Boissons', 'todo'),
  ('Prendre le relais du bar officiel à 01h00 avec le matériel préparé', 'Évènement — Boissons', 'todo'),
  ('Gérer le réapprovisionnement des glacières avec de la glace jusqu’à 04h00', 'Évènement — Boissons', 'todo'),
  ('Installer et ouvrir l’espace enfants : jeux, coloriages, avant leur arrivée', 'Évènement — Enfants', 'todo'),
  ('Superviser les enfants pendant les discours et moments adultes', 'Évènement — Enfants', 'todo'),
  ('Veiller à ce qu’ils dînent à l’heure adaptée', 'Évènement — Enfants', 'todo'),
  ('Anticiper les départs des familles avant minuit', 'Évènement — Enfants', 'todo'),
  ('S’assurer que les personnes âgées sont bien placées à leur table à l’installation dans la salle', 'Évènement — Personnes âgées', 'todo'),
  ('Vérifier régulièrement leur confort : chaleur, volume sonore, accès aux sanitaires', 'Évènement — Personnes âgées', 'todo'),
  ('Organiser leur départ anticipé et leur transport si nécessaire', 'Évènement — Personnes âgées', 'todo'),
  ('Alerter le coordinateur général si un problème de santé survient', 'Évènement — Personnes âgées', 'todo'),
  ('Poser l’urne à son emplacement visible et surveillé dès le début', 'Évènement — Enveloppes & cadeaux', 'todo'),
  ('Surveiller l’urne tout au long de la soirée', 'Évènement — Enveloppes & cadeaux', 'todo'),
  ('Réceptionner et sécuriser les éventuels cadeaux physiques', 'Évènement — Enveloppes & cadeaux', 'todo'),
  ('Récupérer et sécuriser l’urne en fin de soirée avant les adieux', 'Évènement — Enveloppes & cadeaux', 'todo'),
  ('Remettre l’urne et les cadeaux aux fiancés ou à une personne désignée', 'Évènement — Enveloppes & cadeaux', 'todo'),
  ('Avoir la boîte à urgences accessible toute la soirée', 'Évènement — Imprévus', 'todo'),
  ('Gérer les incidents vestimentaires avec le kit couture', 'Évènement — Imprévus', 'todo'),
  ('Avoir sous la main les contacts d’urgence : prestataires, propriétaire du lieu, médecin', 'Évènement — Imprévus', 'todo'),
  ('Prendre les décisions rapidement selon le protocole établi en amont', 'Évènement — Imprévus', 'todo'),
  ('Remonter uniquement ce qui nécessite une décision des fiancés', 'Évènement — Imprévus', 'todo'),
  ('Acheminer les spécialités maison vers le lieu de réception', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Vérifier que toutes les commandes sont complètes et conformes à la réception', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Bloquer l’espace fond de parking réservé aux fiancés avant 17h00', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Vérifier que le micro est opérationnel avant 17h00', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Vérifier que les boissons d’accueil sont en place et au froid avant 17h00', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Vérifier que l’espace enfants est installé et prêt avant 17h00', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Vérifier que les plats spéciaux sont signalés pour le service', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('S’assurer que les tables seront resservies régulièrement pendant le dîner', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Relayer les consignes météo en temps réel si la nuit devient fraîche', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Surveiller les prévisions météo J-7, J-3, J-1 et avoir le plan B intérieur si cocktail en extérieur', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Réaliser les paiements des soldes restants aux prestataires qui partent', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Récupérer les bons de fin de prestation', 'Évènement — Tâches génériques du jour J', 'todo'),
  ('Dire au revoir aux invités qui repartent', 'Désinstallation — Fiancés / lendemain', 'todo'),
  ('Vérifier avec le référent enveloppes l’inventaire du contenu de l’urne', 'Désinstallation — Fiancés / lendemain', 'todo'),
  ('Valider avec le référent logistique que tout le matériel a bien été récupéré', 'Désinstallation — Fiancés / lendemain', 'todo'),
  ('Superviser le rangement en suivant la liste de colisage établie en amont', 'Désinstallation — Logistique rangement', 'todo'),
  ('Trier les éléments : à rendre, à conserver, à jeter', 'Désinstallation — Logistique rangement', 'todo'),
  ('Emballer et étiqueter les caisses pour un retour organisé', 'Désinstallation — Logistique rangement', 'todo'),
  ('Vérifier que rien n’est oublié sur place : vêtements, cadeaux, matériel photo, effets personnels', 'Désinstallation — Logistique rangement', 'todo'),
  ('Retourner le matériel loué dans les délais contractuels', 'Désinstallation — Logistique rangement', 'todo'),
  ('Rendre l’utilitaire loué si pas déjà fait la nuit précédente', 'Désinstallation — Logistique rangement', 'todo'),
  ('Ramener le matériel personnel à la maison', 'Désinstallation — Logistique rangement', 'todo'),
  ('Démonter les éléments de décoration', 'Désinstallation — Décoration', 'todo'),
  ('Trier les éléments loués à rendre et les éléments achetés à conserver', 'Désinstallation — Décoration', 'todo'),
  ('Emballer soigneusement les compositions florales à conserver si souhaité', 'Désinstallation — Décoration', 'todo'),
  ('S’assurer que le lieu est remis dans son état initial : mobilier replacé, nappes retirées, etc.', 'Désinstallation — Décoration', 'todo'),
  ('Inventorier le contenu de l’urne en présence de témoins : Jordan et/ou Sarah', 'Désinstallation — Enveloppes & cadeaux', 'todo'),
  ('Lister les donateurs pour les remerciements personnalisés', 'Désinstallation — Enveloppes & cadeaux', 'todo'),
  ('Remettre l’urne et les cadeaux physiques aux fiancés de façon sécurisée', 'Désinstallation — Enveloppes & cadeaux', 'todo'),
  ('Faire l’état des lieux de sortie avec le propriétaire du lieu', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Vérifier les conditions de restitution du dépôt de garantie', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Prévoir des sacs poubelle pour le tri final des déchets si non géré la nuit précédente', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('S’assurer que tout le matériel loué est restitué ou organisé pour restitution rapide', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Être disponible pour accompagner les invités vers leur hébergement ou leur transport si besoin', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Vérifier que les invités venant de loin ont bien leur moyen de retour organisé', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('S’assurer que les personnes âgées ont un transport retour sécurisé', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Retourner les éléments de location dans les délais contractuels : matériel lumière, glacières, utilitaire', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Vérifier qu’aucun élément loué ne manque ou n’est endommagé avant restitution', 'Désinstallation — Tâches génériques du lendemain', 'todo'),
  ('Envoyer le message de remerciement aux invités préparé en amont', 'Après — Remerciements', 'todo'),
  ('Envoyer un message personnalisé aux prestataires qui ont contribué bénévolement : DJ Djahman, cousins logistique, référents', 'Après — Remerciements', 'todo'),
  ('Remercier chaque donateur d’enveloppe nommément', 'Après — Remerciements', 'todo'),
  ('Remercier les traiteurs et fournisseurs externes avec lesquels tout s’est bien passé', 'Après — Remerciements', 'todo'),
  ('Mettre à jour le tableau de suivi des dépenses avec les dernières dépenses du jour J et du lendemain', 'Après — Clôture financière', 'todo'),
  ('Vérifier que tous les soldes ont bien été réglés', 'Après — Clôture financière', 'todo'),
  ('Récupérer le dépôt de garantie de la salle si non encore restitué', 'Après — Clôture financière', 'todo'),
  ('Clôturer la comptabilité complète et archiver tous les documents et justificatifs', 'Après — Clôture financière', 'todo'),
  ('Archiver les contrats, devis et bons de prestation dans le dossier dédié', 'Après — Clôture financière', 'todo'),
  ('Vérifier que tout le matériel loué a bien été restitué dans les délais', 'Après — Matériel & logistique post-événement', 'todo'),
  ('Signaler tout dommage constaté sur du matériel loué', 'Après — Matériel & logistique post-événement', 'todo'),
  ('Ranger et stocker le matériel acheté : marmite, boîtes, accessoires bar, etc.', 'Après — Matériel & logistique post-événement', 'todo'),
  ('Décider de la destination du stock de boissons restant : conserver ou redistribuer', 'Après — Matériel & logistique post-événement', 'todo'),
  ('Confirmer les délais de livraison des photos/vidéos avec le prestataire', 'Après — Photos & vidéos', 'todo'),
  ('Partager un lien pour que les invités déposent leurs propres photos', 'Après — Photos & vidéos', 'todo'),
  ('Récupérer et sauvegarder les photos du prestataire dès réception', 'Après — Photos & vidéos', 'todo'),
  ('Partager une sélection de photos avec les familles et proches', 'Après — Photos & vidéos', 'todo'),
  ('Retourner les derniers éléments de location si pas encore fait', 'Après — Décoration & fleurs', 'todo'),
  ('Décider du devenir des compositions florales : conserver, offrir, jeter', 'Après — Décoration & fleurs', 'todo'),
  ('Laisser des avis Google ou plateformes pour les prestataires qui l’ont mérité', 'Après — Retours prestataires', 'todo'),
  ('Garder les coordonnées des prestataires pour de futurs événements', 'Après — Retours prestataires', 'todo'),
  ('Faire un debriefing informel avec le coordinateur général pour noter les points à améliorer', 'Après — Retours prestataires', 'todo'),
  ('Rassembler les retours des référents sur ce qui a bien fonctionné et ce qui aurait pu être mieux géré', 'Après — Debriefing général', 'todo'),
  ('Documenter les imprévus rencontrés et les solutions appliquées', 'Après — Debriefing général', 'todo'),
  ('Archiver le conducteur final annoté pour référence future', 'Après — Debriefing général', 'todo');
