-- TODO(checklists) : checklists rattachées à un référent, une mission ou un
-- élément de logistique — à compléter. (Les 59 listes "Feuille de route"
-- fournies par Jordan étaient en réalité des tâches, voir 04_tasks.sql et
-- 0021_remove_standalone_checklists.sql.)
