-- Feuille de route complète fournie par Jordan : 59 checklists "standalone"
-- (aucun owner référent/mission/logistique), organisées par phase × thème.
-- Voir 0014_checklists_standalone_phase.sql pour le changement de schéma.

insert into _20260725_checklists (title, owner_type, phase) values
  ('Avant — Boissons', 'standalone', 'avant'),
  ('Avant — Boîte à urgences', 'standalone', 'avant'),
  ('Avant — Budget & administratif', 'standalone', 'avant'),
  ('Avant — Cadeaux parents', 'standalone', 'avant'),
  ('Avant — Communication aux invités', 'standalone', 'avant'),
  ('Avant — Coordination prestataires et référents', 'standalone', 'avant'),
  ('Avant — DJ / Djahman', 'standalone', 'avant'),
  ('Avant — Discours', 'standalone', 'avant'),
  ('Avant — Décoration', 'standalone', 'avant'),
  ('Avant — Déroulé de la cérémonie', 'standalone', 'avant'),
  ('Avant — Gestion des enfants', 'standalone', 'avant'),
  ('Avant — Gestion des enveloppes', 'standalone', 'avant'),
  ('Avant — Gestion des personnes âgées', 'standalone', 'avant'),
  ('Avant — Gestion du cortège', 'standalone', 'avant'),
  ('Avant — Hébergement invités', 'standalone', 'avant'),
  ('Avant — Lieu / Grand Arbre', 'standalone', 'avant'),
  ('Avant — Location de matériel', 'standalone', 'avant'),
  ('Avant — Photographe / Vidéaste', 'standalone', 'avant'),
  ('Avant — Plan de table', 'standalone', 'avant'),
  ('Avant — Playlist', 'standalone', 'avant'),
  ('Avant — RSVP', 'standalone', 'avant'),
  ('Avant — Rangement', 'standalone', 'avant'),
  ('Avant — Restrictions alimentaires', 'standalone', 'avant'),
  ('Avant — Répétition de la cérémonie', 'standalone', 'avant'),
  ('Avant — Tenue Jordan', 'standalone', 'avant'),
  ('Avant — Tenue Sarah', 'standalone', 'avant'),
  ('Avant — Traiteurs externes & spécialités', 'standalone', 'avant'),
  ('Avant — Transport invités', 'standalone', 'avant'),
  ('Installation — Décoration', 'standalone', 'installation'),
  ('Installation — Fiancés / coordination générale', 'standalone', 'installation'),
  ('Installation — Logistique boissons', 'standalone', 'installation'),
  ('Installation — Spécialités culinaires', 'standalone', 'installation'),
  ('Installation — Tâches génériques de la veille', 'standalone', 'installation'),
  ('Évènement — Accueil invités', 'standalone', 'evenement'),
  ('Évènement — Boissons', 'standalone', 'evenement'),
  ('Évènement — Coordinateur général / avant ouverture', 'standalone', 'evenement'),
  ('Évènement — Coordinateur général / cérémonie', 'standalone', 'evenement'),
  ('Évènement — Coordinateur général / dîner et soirée', 'standalone', 'evenement'),
  ('Évènement — Cortège', 'standalone', 'evenement'),
  ('Évènement — Discours / MC', 'standalone', 'evenement'),
  ('Évènement — Enfants', 'standalone', 'evenement'),
  ('Évènement — Enveloppes & cadeaux', 'standalone', 'evenement'),
  ('Évènement — Fiancés', 'standalone', 'evenement'),
  ('Évènement — Imprévus', 'standalone', 'evenement'),
  ('Évènement — Parking', 'standalone', 'evenement'),
  ('Évènement — Personnes âgées', 'standalone', 'evenement'),
  ('Évènement — Tâches génériques du jour J', 'standalone', 'evenement'),
  ('Désinstallation — Décoration', 'standalone', 'desinstallation'),
  ('Désinstallation — Enveloppes & cadeaux', 'standalone', 'desinstallation'),
  ('Désinstallation — Fiancés / lendemain', 'standalone', 'desinstallation'),
  ('Désinstallation — Logistique rangement', 'standalone', 'desinstallation'),
  ('Désinstallation — Tâches génériques du lendemain', 'standalone', 'desinstallation'),
  ('Après — Clôture financière', 'standalone', 'apres'),
  ('Après — Debriefing général', 'standalone', 'apres'),
  ('Après — Décoration & fleurs', 'standalone', 'apres'),
  ('Après — Matériel & logistique post-événement', 'standalone', 'apres'),
  ('Après — Photos & vidéos', 'standalone', 'apres'),
  ('Après — Remerciements', 'standalone', 'apres'),
  ('Après — Retours prestataires', 'standalone', 'apres');

-- Items des checklists ci-dessus — script fourni par Jordan, rattaché via le
-- titre exact de la checklist (voir l'insert juste au-dessus).
begin;

with seed(checklist_title, label, is_done, sort_order) as (
values
  ('Avant — Budget & administratif', 'Alimenter le tableau de suivi des dépenses avec toutes les dépenses engagées à ce jour', false, 1),
  ('Avant — Budget & administratif', 'Créer l’échéancier des paiements restants par prestataire avec dates limites', false, 2),
  ('Avant — Budget & administratif', 'Effectuer les paiements aux dates prévues et conserver tous les justificatifs', false, 3),
  ('Avant — Budget & administratif', 'Préparer les enveloppes de paiement espèces pour le jour J si nécessaire', false, 4),
  ('Avant — Budget & administratif', 'Vérifier les conditions d’annulation dans chaque contrat', false, 5),
  ('Avant — Budget & administratif', 'Définir et réserver l’enveloppe imprévus (5–10 % du budget total)', false, 6),
  ('Avant — Budget & administratif', 'Centraliser tous les contrats dans un dossier unique numérique', false, 7),
  ('Avant — Budget & administratif', 'Vérifier les plafonds bancaires et contacter la banque si des virements importants sont prévus', false, 8),
  ('Avant — Lieu / Grand Arbre', 'Envoyer le déroulé minuté au Grand Arbre', false, 1),
  ('Avant — Lieu / Grand Arbre', 'Demander si l’accès est possible la veille pour décoration et dépôt des boissons', false, 2),
  ('Avant — Lieu / Grand Arbre', 'Communiquer le nombre définitif d’invités au Grand Arbre', false, 3),
  ('Avant — Lieu / Grand Arbre', 'Confirmer le nombre exact de tables disponibles', false, 4),
  ('Avant — Lieu / Grand Arbre', 'Planifier la visite technique avec le DJ — premier week-end de juillet', false, 5),
  ('Avant — Lieu / Grand Arbre', 'Établir le plan de salle par zones : accueil, cocktail, dîner, danse, enfants', false, 6),
  ('Avant — Lieu / Grand Arbre', 'Valider le menu définitif avec le traiteur du lieu', false, 7),
  ('Avant — Lieu / Grand Arbre', 'Valider le timing de service : cocktail, plat, dessert, café', false, 8),
  ('Avant — Lieu / Grand Arbre', 'Confirmer exactement ce qui est inclus dans la prestation nettoyage, notamment les poubelles', false, 9),
  ('Avant — Lieu / Grand Arbre', 'Clarifier la procédure d’état des lieux de sortie avec le propriétaire', false, 10),
  ('Avant — Lieu / Grand Arbre', 'Préparer la signalétique de bienvenue et le fléchage depuis le parking', false, 11),
  ('Avant — Lieu / Grand Arbre', 'Faire la visite technique avec le DJ — premier week-end de juillet', false, 12),
  ('Avant — Lieu / Grand Arbre', 'Tester sur place que la sono de Djahman couvre bien l’espace extérieur du Grand Arbre', false, 13),
  ('Avant — Lieu / Grand Arbre', 'Simuler le parcours du cortège et vérifier que le son porte jusqu’au fond', false, 14),
  ('Avant — Traiteurs externes & spécialités', 'Commander les spécialités malgaches : prestataire, quantités, date de livraison', false, 1),
  ('Avant — Traiteurs externes & spécialités', 'Formaliser la recette des spécialités indiennes', false, 2),
  ('Avant — Traiteurs externes & spécialités', 'Définir les quantités des spécialités indiennes', false, 3),
  ('Avant — Traiteurs externes & spécialités', 'Acheter les épices pour les spécialités indiennes', false, 4),
  ('Avant — Traiteurs externes & spécialités', 'Couper les ingrédients : ail, tomates, oignons, cressons', false, 5),
  ('Avant — Traiteurs externes & spécialités', 'Commander les bonbons piments', false, 6),
  ('Avant — Traiteurs externes & spécialités', 'Valider avec Christiana qu’on peut préparer les mini bokits à la maison', false, 7),
  ('Avant — Traiteurs externes & spécialités', 'Acheter les ingrédients des spécialités guadeloupéennes', false, 8),
  ('Avant — Traiteurs externes & spécialités', 'Proposer 3 garnitures : jambon halal/fromage, poulet, thon', false, 9),
  ('Avant — Traiteurs externes & spécialités', 'Acheter une grande marmite adaptée à la friture en grande quantité, environ 40 cm', false, 10),
  ('Avant — Traiteurs externes & spécialités', 'Prévoir 30 cartons alimentaires adaptés au transport des fritures et spécialités fragiles', false, 11),
  ('Avant — Traiteurs externes & spécialités', 'Planifier qui prépare quoi, où et quand : veille ou matin du jour J', false, 12),
  ('Avant — Boissons', 'Maintenir le fichier Excel du stock local à jour avec les quantités exactes', false, 1),
  ('Avant — Boissons', 'Louer un utilitaire pour le transport des boissons la veille', false, 2),
  ('Avant — Boissons', 'Recruter des cousins pour aider au chargement à la maison et au déchargement à la salle', false, 3),
  ('Avant — Boissons', 'Louer ou acheter le matériel bar pour la période 1h–4h : glacières, bacs à glaçons, seaux, pinces', false, 4),
  ('Avant — Boissons', 'Calculer la quantité de glace nécessaire pour tenir jusqu’à 4h en plein été', false, 5),
  ('Avant — Boissons', 'Désigner le responsable boissons jour J', false, 6),
  ('Avant — Location de matériel', 'Lister tout le matériel à louer : jeux de lumières, glacières supplémentaires, panneaux de signalétique, mobilier éventuel', false, 1),
  ('Avant — Location de matériel', 'Confirmer avec Djahman ce qu’il apporte en éclairage et ce qui reste à prévoir', false, 2),
  ('Avant — Location de matériel', 'Demander des devis pour la location du matériel lumière manquant', false, 3),
  ('Avant — Location de matériel', 'Réserver le matériel auprès d’un loueur', false, 4),
  ('Avant — Location de matériel', 'Arbitrer acheter vs louer pour chaque élément : glacières, panneaux, etc.', false, 5),
  ('Avant — RSVP', 'Envoyer un message à tous les participants confirmés : remerciements + choix du plat poulet ou poisson', false, 1),
  ('Avant — RSVP', 'Relancer les retardataires n’ayant pas encore répondu', false, 2),
  ('Avant — RSVP', 'Recueillir les horaires d’arrivée de chaque invité : vol, train, voiture', false, 3),
  ('Avant — RSVP', 'Compiler le tableau final : nom, présence, plat, horaire d’arrivée, besoins transport', false, 4),
  ('Avant — RSVP', 'Communiquer les chiffres définitifs au Grand Arbre : traiteur + salle', false, 5),
  ('Avant — Hébergement invités', 'Hôtels identifiés, codes promo obtenus et guide invités envoyé', true, 1),
  ('Avant — Hébergement invités', 'Vérifier que tous les invités venant de loin ont bien reçu le guide hébergement', false, 2),
  ('Avant — Hébergement invités', 'Demander qui loge où', false, 3),
  ('Avant — Transport invités', 'Cartographier les besoins en transport le jour J à partir des horaires d’arrivée collectés', false, 1),
  ('Avant — Transport invités', 'Identifier les invités sans moyen de retour tard dans la nuit et prévoir un VTC/taxi', false, 2),
  ('Avant — Transport invités', 'Communiquer les modalités de transport à tous les invités concernés', false, 3),
  ('Avant — Transport invités', 'Noter le contact VTC/taxi de nuit à avoir sous la main le jour J', false, 4),
  ('Avant — DJ / Djahman', 'Mail de brief envoyé à Djahman le 22 juin', true, 1),
  ('Avant — DJ / Djahman', 'S’assurer que Djahman a bien répondu au Google Forms', false, 2),
  ('Avant — DJ / Djahman', 'Obtenir confirmation du matériel : sono mobile extérieur, sono salle, diffusion terrasse, micros sans fil', false, 3),
  ('Avant — DJ / Djahman', 'Confirmer que le matériel est adapté à environ 90 personnes', false, 4),
  ('Avant — DJ / Djahman', 'Obtenir ses besoins en alimentation électrique pour anticiper avec le lieu', false, 5),
  ('Avant — DJ / Djahman', 'Confirmer son heure d’arrivée souhaitée et le temps nécessaire à l’installation', false, 6),
  ('Avant — DJ / Djahman', 'Obtenir ses recommandations pour l’éclairage de la soirée dansante', false, 7),
  ('Avant — DJ / Djahman', 'Planifier sa venue pour la visite technique début juillet', false, 8),
  ('Avant — DJ / Djahman', 'Valider la version extended 30 min du morceau d’entrée du cortège', false, 9),
  ('Avant — DJ / Djahman', 'Confirmer “A love song” – Garth Stevenson pour l’arrivée de Sarah', false, 10),
  ('Avant — DJ / Djahman', 'Confirmer “Se pas pou dat” – Zo konpa / Konpa Lakay pour la présentation de la bague', false, 11),
  ('Avant — DJ / Djahman', 'Définir ensemble les musiques du cocktail et du repas', false, 12),
  ('Avant — DJ / Djahman', 'Convenir du canal de communication discret le jour J : intermédiaire ou SMS', false, 13),
  ('Avant — Playlist', 'Référentiel Excel + Spotify transmis', true, 1),
  ('Avant — Playlist', 'S’assurer que Djahman a bien ouvert le fichier Excel référentiel', false, 2),
  ('Avant — Playlist', 'Lui transmettre les morceaux disponibles sur YouTube uniquement, hors Spotify', false, 3),
  ('Avant — Playlist', 'Valider avec lui la structure de la soirée dansante : blocs, transitions, montée progressive', false, 4),
  ('Avant — Playlist', 'Confirmer les morceaux “priorité à notre sélection” : Seggae, Salegy malgache, Bollywood, Pop indienne, Arabic', false, 5),
  ('Avant — Photographe / Vidéaste', 'Contrat signé et acompte versé', true, 1),
  ('Avant — Photographe / Vidéaste', 'Créer le groupe WhatsApp avec les deux numéros + 07 84 96 72 89', false, 2),
  ('Avant — Photographe / Vidéaste', 'Partager le déroulé de la journée dans le groupe dès qu’il est finalisé', false, 3),
  ('Avant — Photographe / Vidéaste', 'Rassembler des inspirations photo/vidéo : style, ambiance, cadrage', false, 4),
  ('Avant — Photographe / Vidéaste', 'Rédiger la shot list : photos indispensables, familles, moments clés, portraits officiels', false, 5),
  ('Avant — Photographe / Vidéaste', 'Confirmer l’heure d’arrivée souhaitée avant les invités pour salle vide + préparatifs', false, 6),
  ('Avant — Photographe / Vidéaste', 'Prévenir les familles en amont de limiter les téléphones pendant la cérémonie', false, 7),
  ('Avant — Décoration', 'Définir le thème visuel et la palette de couleurs', false, 1),
  ('Avant — Décoration', 'Lister les éléments déco par zone : entrée, cortège, table d’honneur, tables invités, espace danse', false, 2),
  ('Avant — Décoration', 'Contacter et choisir un fleuriste', false, 3),
  ('Avant — Décoration', 'Valider les compositions florales et les tarifs', false, 4),
  ('Avant — Décoration', 'Comparer achat, location et DIY pour chaque élément puis arbitrer', false, 5),
  ('Avant — Décoration', 'Créer le plan de décoration par zone avec photos de référence', false, 6),
  ('Avant — Décoration', 'Commander ou acquérir tous les éléments déco avec délais de livraison compatibles', false, 7),
  ('Avant — Décoration', 'Confirmer la livraison des fleurs : heure, lieu, référent sur place', false, 8),
  ('Avant — Tenue Sarah', 'Vêtement reçu', true, 1),
  ('Avant — Tenue Sarah', 'Trouver et commander les chaussures assorties', false, 2),
  ('Avant — Tenue Sarah', 'Trouver et commander les bijoux assortis', false, 3),
  ('Avant — Tenue Sarah', 'Organiser un essayage complet tenue + chaussures', false, 4),
  ('Avant — Tenue Sarah', 'Laver et repasser le lehenga dans un pressing', false, 5),
  ('Avant — Tenue Sarah', 'Choisir le style de coiffure', false, 6),
  ('Avant — Tenue Sarah', 'Trouver la coiffeuse', false, 7),
  ('Avant — Tenue Sarah', 'Faire un essai coiffure', false, 8),
  ('Avant — Tenue Sarah', 'Réserver la coiffeuse pour le jour J', false, 9),
  ('Avant — Tenue Sarah', 'Réaliser un essai maquillage', false, 10),
  ('Avant — Tenue Sarah', 'Prendre le rendez-vous de maquillage pour le jour J', false, 11),
  ('Avant — Tenue Sarah', 'Trouver des faux ongles', false, 12),
  ('Avant — Tenue Jordan', 'Identifier et commander la tenue définitive avec délai de livraison confirmé', false, 1),
  ('Avant — Tenue Jordan', 'Prévoir les retouches si nécessaire', false, 2),
  ('Avant — Tenue Jordan', 'Trouver et commander les chaussures assorties', false, 3),
  ('Avant — Tenue Jordan', 'Choisir les accessoires : pochette, montre, etc.', false, 4),
  ('Avant — Tenue Jordan', 'Faire un essayage complet tenue + chaussures avant le jour J', false, 5),
  ('Avant — Tenue Jordan', 'RDV coiffure pris le 25/07 à 10h', true, 6),
  ('Avant — Tenue Jordan', 'Vérifier si le rendez-vous coiffure existant doit être maintenu, décalé ou confirmé', false, 7),
  ('Avant — Discours', 'Désigner un MC / coordinateur discours pour les transitions', false, 1),
  ('Avant — Discours', 'Prévoir un micro-test avec les parents', false, 2),
  ('Avant — Déroulé de la cérémonie', 'Rédiger le conducteur minuté complet : accueil, cortège, cérémonie, cocktail, dîner, soirée, remerciements, fin', false, 1),
  ('Avant — Déroulé de la cérémonie', 'Valider le conducteur avec tous les prestataires clés : DJ, traiteur, photographe', false, 2),
  ('Avant — Déroulé de la cérémonie', 'Faire le point avec les parents de Sarah sur leurs interventions pendant la cérémonie', false, 3),
  ('Avant — Déroulé de la cérémonie', 'Identifier les temps morts et prévoir des animations ou transitions', false, 4),
  ('Avant — Déroulé de la cérémonie', 'Gérer la chaleur pour les invités pendant la cérémonie extérieure : ombre, eau fraîche, éventails', false, 5),
  ('Avant — Déroulé de la cérémonie', 'Faire le point avec les parents de Jordan sur leurs interventions pendant la cérémonie', false, 6),
  ('Avant — Déroulé de la cérémonie', 'Désigner un maître de cérémonie / coordinateur de soirée : Lisa', true, 7),
  ('Avant — Déroulé de la cérémonie', 'Prévoir un plan B pour chaque moment critique : météo, retard prestataire, son défaillant', false, 8),
  ('Avant — Déroulé de la cérémonie', 'Imprimer le conducteur en plusieurs exemplaires pour le jour J', false, 9),
  ('Avant — Plan de table', 'Récupérer auprès du Grand Arbre le nombre exact de tables et leur capacité', false, 1),
  ('Avant — Plan de table', 'Créer les marque-places pour le plat et les numéros de table', false, 2),
  ('Avant — Plan de table', 'Imprimer le plan de table pour affichage à l’entrée de la salle', false, 3),
  ('Avant — Plan de table', 'Réaliser un premier plan de table et le valider avec Sarah', false, 4),
  ('Avant — Plan de table', 'Intégrer les contraintes : mobilité réduite, personnes âgées, enfants, affinités / tensions', false, 5),
  ('Avant — Restrictions alimentaires', 'Données collectées via RSVP', true, 1),
  ('Avant — Restrictions alimentaires', 'Définir le système d’identification à table : marque-place codé, étiquette discrète, etc.', false, 2),
  ('Avant — Restrictions alimentaires', 'Signaler les allergies sévères à l’ensemble de l’équipe de service', false, 3),
  ('Avant — Restrictions alimentaires', 'Préparer la signalétique pour les plats des buffets et amuse-bouches : allergènes, halal, végé, etc.', false, 4),
  ('Avant — Cadeaux parents', 'Décider si un cadeau ou une attention est prévu pour les parents', false, 1),
  ('Avant — Cadeaux parents', 'Choisir le type de cadeau, commander avec délai compatible et organiser la distribution le jour J', false, 2),
  ('Avant — Communication aux invités', 'Save the date et invitations envoyés', true, 1),
  ('Avant — Communication aux invités', 'Envoyer un message individuel ou par famille : remerciement RSVP + choix poulet/poisson + horaire d’arrivée attendu', false, 2),
  ('Avant — Communication aux invités', 'Envoyer un rappel général J-7 avec programme, accès, parking, dress code, météo anticipée', false, 3),
  ('Avant — Communication aux invités', 'Rédiger le message de remerciement post-événement à l’avance', false, 4),
  ('Avant — Coordination prestataires et référents', 'Lister tous les prestataires professionnels et amis avec rôle, contact et horaire d’intervention', false, 1),
  ('Avant — Coordination prestataires et référents', 'Avoir un numéro de contact de secours pour chaque prestataire clé', false, 2),
  ('Avant — Coordination prestataires et référents', 'Créer un document de coordination partagé accessible à tous les référents', false, 3),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent logistique boissons', false, 4),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent décoration', false, 5),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent spécialités culinaires', false, 6),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent fleurs', false, 7),
  ('Avant — Coordination prestataires et référents', 'Désigner le coordinateur général', false, 8),
  ('Avant — Coordination prestataires et référents', 'Désigner les référents accueil invités', false, 9),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent enfants', false, 10),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent personnes âgées', false, 11),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent cortège', false, 12),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent discours / MC', false, 13),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent enveloppes & cadeaux', false, 14),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent parking', false, 15),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent boissons', false, 16),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent imprévus', false, 17),
  ('Avant — Coordination prestataires et référents', 'Désigner le référent logistique rangement', false, 18),
  ('Avant — Coordination prestataires et référents', 'Contacter chaque référent pour confirmer son accord, son périmètre et lui fournir une boîte à outils', false, 19),
  ('Avant — Coordination prestataires et référents', 'Organiser une réunion de coordination 1–2 semaines avant, idéalement lors de la visite technique', false, 20),
  ('Avant — Coordination prestataires et référents', 'Désigner un interlocuteur unique sur place pour tous les prestataires', false, 21),
  ('Avant — Gestion du cortège', 'Définir la composition et l’ordre du cortège', false, 1),
  ('Avant — Gestion du cortège', 'Prévenir chaque personne du cortège de son rôle et de ce qu’elle devra faire', false, 2),
  ('Avant — Gestion du cortège', 'Choisir et synchroniser les musiques d’entrée avec Djahman', false, 3),
  ('Avant — Gestion du cortège', 'Prévoir les alternatives pour les personnes à mobilité réduite', false, 4),
  ('Avant — Gestion du cortège', 'Trouver un plateau de présentation et l’orner', false, 5),
  ('Avant — Répétition de la cérémonie', 'Découper la répétition de la cérémonie en séquences à répéter', false, 1),
  ('Avant — Répétition de la cérémonie', 'Organiser la répétition avec les personnes clés du cortège et de la cérémonie', false, 2),
  ('Avant — Gestion des enfants', 'Recenser le nombre d’enfants présents et leurs âges', false, 1),
  ('Avant — Gestion des enfants', 'Prévoir le contenu de l’espace enfants : jeux, coloriages, tapis', false, 2),
  ('Avant — Gestion des enfants', 'Confirmer avec le traiteur le menu enfants et les horaires adaptés', false, 3),
  ('Avant — Gestion des personnes âgées', 'Identifier les personnes âgées ou à mobilité réduite dans la liste des invités', false, 1),
  ('Avant — Gestion des personnes âgées', 'Prévoir leur placement à une table accessible : proche sortie, sanitaires, sans marche', false, 2),
  ('Avant — Gestion des personnes âgées', 'Anticiper leur départ anticipé et prévoir un transport si nécessaire', false, 3),
  ('Avant — Gestion des enveloppes', 'Choisir et préparer l’urne ou boîte sécurisée', false, 1),
  ('Avant — Gestion des enveloppes', 'Désigner une personne de confiance pour gérer l’urne toute la soirée', false, 2),
  ('Avant — Rangement', 'Établir la liste de colisage : ce qui part de la maison, ce qui vient du local, ce qui repart où', false, 1),
  ('Avant — Rangement', 'Désigner l’équipe de rangement post-soirée, distincte de l’équipe installation', false, 2),
  ('Avant — Boîte à urgences', 'Constituer la boîte à urgences : ruban adhésif, épingles, médicaments de base, chargeur, monnaie, anti-moustiques', false, 1),
  ('Avant — Boîte à urgences', 'Préparer le kit couture / tenue de rechange pour incidents vestimentaires', false, 2),
  ('Avant — Boîte à urgences', 'Compiler la liste des contacts d’urgence : prestataires, propriétaire du lieu, médecin', false, 3),
  ('Installation — Fiancés / coordination générale', 'Valider l’installation déco avant de partir', false, 1),
  ('Installation — Fiancés / coordination générale', 'Faire le tour de contrôle final de la salle', false, 2),
  ('Installation — Fiancés / coordination générale', 'Rappeler aux intervenants des discours leur ordre de passage et leur durée', false, 3),
  ('Installation — Fiancés / coordination générale', 'S’assurer que tous les référents ont reçu le conducteur imprimé', false, 4),
  ('Installation — Fiancés / coordination générale', 'Préparer les tenues respectives pour le lendemain : rangées, accessoires prêts', false, 5),
  ('Installation — Fiancés / coordination générale', 'Confirmer les horaires de chacun pour le lendemain matin', false, 6),
  ('Installation — Logistique boissons', 'Récupérer l’utilitaire loué tôt le matin', false, 1),
  ('Installation — Logistique boissons', 'Organiser le chargement depuis le local avec les cousins mobilisés', false, 2),
  ('Installation — Logistique boissons', 'Acheminer les boissons au Grand Arbre', false, 3),
  ('Installation — Logistique boissons', 'Superviser le déchargement et le rangement dans l’espace prévu', false, 4),
  ('Installation — Logistique boissons', 'Organiser la mise au froid : champagne, despé, jus, coca dans les glacières ou frigo du lieu', false, 5),
  ('Installation — Logistique boissons', 'Ranger et sécuriser le matériel bar de relais : glacières supplémentaires, seaux, pinces', false, 6),
  ('Installation — Logistique boissons', 'Vérifier les quantités à l’arrivée par rapport au fichier Excel de stock', false, 7),
  ('Installation — Décoration', 'Installer les éléments structurants en premier : backdrop, arches, nappes', false, 1),
  ('Installation — Décoration', 'Disposer la décoration de table : centres de table, marque-places, bougies, numéros', false, 2),
  ('Installation — Décoration', 'Installer la signalétique : plan de table à l’entrée, panneau bienvenue, numéros de table', false, 3),
  ('Installation — Décoration', 'Tester et ajuster l’éclairage décoratif', false, 4),
  ('Installation — Décoration', 'Réceptionner les compositions florales du fleuriste', false, 5),
  ('Installation — Décoration', 'Vérifier que les compositions sont conformes à la commande', false, 6),
  ('Installation — Décoration', 'Mettre de l’eau dans les vases si livraison anticipée', false, 7),
  ('Installation — Décoration', 'Photographier la salle terminée et envoyer aux fiancés pour validation', false, 8),
  ('Installation — Spécialités culinaires', 'Réceptionner les spécialités malgaches et indiennes commandées et vérifier leur conformité', false, 1),
  ('Installation — Spécialités culinaires', 'Superviser la préparation des spécialités guadeloupéennes à la maison', false, 2),
  ('Installation — Spécialités culinaires', 'Préparer les fritures en grande quantité avec la marmite dédiée', false, 3),
  ('Installation — Spécialités culinaires', 'Conditionner toutes les spécialités dans les boîtes de transport adaptées', false, 4),
  ('Installation — Spécialités culinaires', 'S’assurer que tout est prêt et conditionné pour le lendemain matin', false, 5),
  ('Installation — Spécialités culinaires', 'Ranger les spécialités dans un endroit frais et sécurisé jusqu’au transport le jour J', false, 6),
  ('Installation — Tâches génériques de la veille', 'Confirmer les horaires d’arrivée de chacun le lendemain avec tous les référents', false, 1),
  ('Installation — Tâches génériques de la veille', 'Confirmer avec le Grand Arbre l’accès pour le lendemain : heure d’ouverture, point d’entrée', false, 2),
  ('Installation — Tâches génériques de la veille', 'Confirmer l’heure d’arrivée du DJ à 16h30 et du photographe/vidéaste', false, 3),
  ('Installation — Tâches génériques de la veille', 'Imprimer et distribuer le conducteur à tous les référents', false, 4),
  ('Installation — Tâches génériques de la veille', 'Vérifier que les enveloppes de paiement espèces jour J sont prêtes', false, 5),
  ('Installation — Tâches génériques de la veille', 'Rappeler aux intervenants des discours leur ordre de passage et leur durée', false, 6),
  ('Installation — Tâches génériques de la veille', 'Préparer la boîte à urgences si ce n’est pas déjà fait', false, 7),
  ('Installation — Tâches génériques de la veille', 'Organiser le stockage des boissons au Grand Arbre selon le planning de refroidissement', false, 8),
  ('Installation — Tâches génériques de la veille', 'Vérifier que le champagne est bien au froid pour le lendemain dès 17h', false, 9),
  ('Installation — Tâches génériques de la veille', 'Calculer et commander la glace nécessaire si livraison possible la veille', false, 10),
  ('Installation — Tâches génériques de la veille', 'Confirmer que le plan de décoration par zone avec photos de référence est imprimé ou accessible', false, 11),
  ('Installation — Tâches génériques de la veille', 'Vérifier que les marque-places et numéros de table sont prêts', false, 12),
  ('Installation — Tâches génériques de la veille', 'Préparer les panneaux de signalétique parking', false, 13),
  ('Installation — Tâches génériques de la veille', 'Faire le tour de contrôle de la salle : déco, boissons au froid, mobilier en place', false, 14),
  ('Installation — Tâches génériques de la veille', 'Vérifier que les bonbons piments réunionnais sont réceptionnés et conditionnés', false, 15),
  ('Installation — Tâches génériques de la veille', 'Vérifier que l’urne enveloppes est prête et placée à son emplacement', false, 16),
  ('Installation — Tâches génériques de la veille', 'S’assurer que rien ne manque en comparant à la liste de colisage', false, 17),
  ('Évènement — Fiancés', 'Être prêts : tenue, coiffure, maquillage avant 17h00', false, 1),
  ('Évènement — Fiancés', 'Donner le signal de départ du conducteur au coordinateur général', false, 2),
  ('Évènement — Coordinateur général / avant ouverture', 'Accueillir le DJ à 16h30, lui montrer l’espace, vérifier branchements et soundcheck', false, 1),
  ('Évènement — Coordinateur général / avant ouverture', 'S’assurer que le DJ dispose d’eau et d’un espace de pause', false, 2),
  ('Évènement — Coordinateur général / avant ouverture', 'Accueillir le photographe/vidéaste, lui remettre la shot list et le conducteur', false, 3),
  ('Évènement — Coordinateur général / avant ouverture', 'Présenter au photographe/vidéaste les personnes clés dès que possible', false, 4),
  ('Évènement — Coordinateur général / avant ouverture', 'Faire le tour de contrôle final de la salle avant l’arrivée des invités', false, 5),
  ('Évènement — Coordinateur général / avant ouverture', 'Vérifier que le micro est opérationnel', false, 6),
  ('Évènement — Coordinateur général / cérémonie', 'Synchroniser les montres ou téléphones avec le DJ et le photographe', false, 1),
  ('Évènement — Coordinateur général / cérémonie', 'Superviser le positionnement des placeurs pour l’accueil des invités', false, 2),
  ('Évènement — Coordinateur général / cérémonie', 'Donner le signal de départ du cortège à 17h30', false, 3),
  ('Évènement — Coordinateur général / cérémonie', 'Suivre le conducteur minute par minute pendant toute la cérémonie', false, 4),
  ('Évènement — Coordinateur général / cérémonie', 'Communiquer avec le DJ via signal discret', false, 5),
  ('Évènement — Coordinateur général / cérémonie', 'Alerter discrètement si un retard se creuse', false, 6),
  ('Évènement — Coordinateur général / cérémonie', 'Superviser la transition cérémonie → cocktail → salle de réception', false, 7),
  ('Évènement — Coordinateur général / dîner et soirée', 'Confirmer l’heure de début du service avec le responsable traiteur', false, 1),
  ('Évènement — Coordinateur général / dîner et soirée', 'Surveiller le timing entre les plats pour rester dans le conducteur', false, 2),
  ('Évènement — Coordinateur général / dîner et soirée', 'Signaler au traiteur tout changement de programme', false, 3),
  ('Évènement — Coordinateur général / dîner et soirée', 'Signaler au DJ les transitions importantes : premier slow, montée dancefloor, clôture', false, 4),
  ('Évènement — Coordinateur général / dîner et soirée', 'Valider avec le traiteur les horaires du dessert à 23h00, du café et du départ de l’équipe', false, 5),
  ('Évènement — Coordinateur général / dîner et soirée', 'Confirmer l’heure de fin de prestation du DJ et la musique de clôture', false, 6),
  ('Évènement — Parking', 'Poser la signalétique directionnelle depuis l’accès principal', false, 1),
  ('Évènement — Parking', 'Bloquer ou signaler l’espace fond de parking réservé aux fiancés', false, 2),
  ('Évènement — Parking', 'Orienter chaque voiture vers l’entrée du parking', false, 3),
  ('Évènement — Parking', 'Avoir le contact du propriétaire du lieu pour toute voiture à déplacer si nécessaire', false, 4),
  ('Évènement — Parking', 'Informer le coordinateur général quand les arrivées se stabilisent vers 18h15', false, 5),
  ('Évènement — Accueil invités', 'Vérifier que la signalétique d’accueil est en place : plan de table affiché, fléchage terrasse', false, 1),
  ('Évènement — Accueil invités', 'Pointer les arrivées sur la liste de présence', false, 2),
  ('Évènement — Accueil invités', 'Orienter chaque invité vers la terrasse cocktail', false, 3),
  ('Évènement — Accueil invités', 'S’assurer que les boissons d’accueil sont disponibles dès 17h00', false, 4),
  ('Évènement — Accueil invités', 'Gérer les arrivées tardives avec discrétion pendant la cérémonie', false, 5),
  ('Évènement — Cortège', 'Rassembler les membres du cortège à 17h20', false, 1),
  ('Évènement — Cortège', 'Vérifier que chacun connaît sa place et son rôle', false, 2),
  ('Évènement — Cortège', 'Coordonner avec le DJ le signal de lancement de la musique d’entrée', false, 3),
  ('Évènement — Cortège', 'Donner le signal de départ au premier rang du cortège', false, 4),
  ('Évènement — Cortège', 'Briefer le photographe sur le déroulé du cortège juste avant', false, 5),
  ('Évènement — Discours / MC', 'Tester le micro et le retour son avant le premier discours', false, 1),
  ('Évènement — Discours / MC', 'Coordonner avec le DJ la musique de fond éventuelle', false, 2),
  ('Évènement — Discours / MC', 'Annoncer et remercier chaque intervenant avec fluidité', false, 3),
  ('Évènement — Discours / MC', 'Gérer le timing discrètement si un orateur dépasse', false, 4),
  ('Évènement — Discours / MC', 'S’assurer que chaque orateur a son texte sur papier ou téléphone chargé', false, 5),
  ('Évènement — Boissons', 'Vérifier à l’ouverture que les boissons d’accueil sont en place et au froid', false, 1),
  ('Évènement — Boissons', 'Superviser le service des boissons pendant le cocktail', false, 2),
  ('Évènement — Boissons', 'S’assurer que les tables sont régulièrement resservies en eau et boissons pendant le dîner', false, 3),
  ('Évènement — Boissons', 'Prendre le relais du bar officiel à 01h00 avec le matériel préparé', false, 4),
  ('Évènement — Boissons', 'Gérer le réapprovisionnement des glacières avec de la glace jusqu’à 04h00', false, 5),
  ('Évènement — Enfants', 'Installer et ouvrir l’espace enfants : jeux, coloriages, avant leur arrivée', false, 1),
  ('Évènement — Enfants', 'Superviser les enfants pendant les discours et moments adultes', false, 2),
  ('Évènement — Enfants', 'Veiller à ce qu’ils dînent à l’heure adaptée', false, 3),
  ('Évènement — Enfants', 'Anticiper les départs des familles avant minuit', false, 4),
  ('Évènement — Personnes âgées', 'S’assurer que les personnes âgées sont bien placées à leur table à l’installation dans la salle', false, 1),
  ('Évènement — Personnes âgées', 'Vérifier régulièrement leur confort : chaleur, volume sonore, accès aux sanitaires', false, 2),
  ('Évènement — Personnes âgées', 'Organiser leur départ anticipé et leur transport si nécessaire', false, 3),
  ('Évènement — Personnes âgées', 'Alerter le coordinateur général si un problème de santé survient', false, 4),
  ('Évènement — Enveloppes & cadeaux', 'Poser l’urne à son emplacement visible et surveillé dès le début', false, 1),
  ('Évènement — Enveloppes & cadeaux', 'Surveiller l’urne tout au long de la soirée', false, 2),
  ('Évènement — Enveloppes & cadeaux', 'Réceptionner et sécuriser les éventuels cadeaux physiques', false, 3),
  ('Évènement — Enveloppes & cadeaux', 'Récupérer et sécuriser l’urne en fin de soirée avant les adieux', false, 4),
  ('Évènement — Enveloppes & cadeaux', 'Remettre l’urne et les cadeaux aux fiancés ou à une personne désignée', false, 5),
  ('Évènement — Imprévus', 'Avoir la boîte à urgences accessible toute la soirée', false, 1),
  ('Évènement — Imprévus', 'Gérer les incidents vestimentaires avec le kit couture', false, 2),
  ('Évènement — Imprévus', 'Avoir sous la main les contacts d’urgence : prestataires, propriétaire du lieu, médecin', false, 3),
  ('Évènement — Imprévus', 'Prendre les décisions rapidement selon le protocole établi en amont', false, 4),
  ('Évènement — Imprévus', 'Remonter uniquement ce qui nécessite une décision des fiancés', false, 5),
  ('Évènement — Tâches génériques du jour J', 'Acheminer les spécialités maison vers le lieu de réception', false, 1),
  ('Évènement — Tâches génériques du jour J', 'Vérifier que toutes les commandes sont complètes et conformes à la réception', false, 2),
  ('Évènement — Tâches génériques du jour J', 'Bloquer l’espace fond de parking réservé aux fiancés avant 17h00', false, 3),
  ('Évènement — Tâches génériques du jour J', 'Vérifier que le micro est opérationnel avant 17h00', false, 4),
  ('Évènement — Tâches génériques du jour J', 'Vérifier que les boissons d’accueil sont en place et au froid avant 17h00', false, 5),
  ('Évènement — Tâches génériques du jour J', 'Vérifier que l’espace enfants est installé et prêt avant 17h00', false, 6),
  ('Évènement — Tâches génériques du jour J', 'Vérifier que les plats spéciaux sont signalés pour le service', false, 7),
  ('Évènement — Tâches génériques du jour J', 'S’assurer que les tables seront resservies régulièrement pendant le dîner', false, 8),
  ('Évènement — Tâches génériques du jour J', 'Relayer les consignes météo en temps réel si la nuit devient fraîche', false, 9),
  ('Évènement — Tâches génériques du jour J', 'Surveiller les prévisions météo J-7, J-3, J-1 et avoir le plan B intérieur si cocktail en extérieur', false, 10),
  ('Évènement — Tâches génériques du jour J', 'Réaliser les paiements des soldes restants aux prestataires qui partent', false, 11),
  ('Évènement — Tâches génériques du jour J', 'Récupérer les bons de fin de prestation', false, 12),
  ('Désinstallation — Fiancés / lendemain', 'Dire au revoir aux invités qui repartent', false, 1),
  ('Désinstallation — Fiancés / lendemain', 'Vérifier avec le référent enveloppes l’inventaire du contenu de l’urne', false, 2),
  ('Désinstallation — Fiancés / lendemain', 'Valider avec le référent logistique que tout le matériel a bien été récupéré', false, 3),
  ('Désinstallation — Logistique rangement', 'Superviser le rangement en suivant la liste de colisage établie en amont', false, 1),
  ('Désinstallation — Logistique rangement', 'Trier les éléments : à rendre, à conserver, à jeter', false, 2),
  ('Désinstallation — Logistique rangement', 'Emballer et étiqueter les caisses pour un retour organisé', false, 3),
  ('Désinstallation — Logistique rangement', 'Vérifier que rien n’est oublié sur place : vêtements, cadeaux, matériel photo, effets personnels', false, 4),
  ('Désinstallation — Logistique rangement', 'Retourner le matériel loué dans les délais contractuels', false, 5),
  ('Désinstallation — Logistique rangement', 'Rendre l’utilitaire loué si pas déjà fait la nuit précédente', false, 6),
  ('Désinstallation — Logistique rangement', 'Ramener le matériel personnel à la maison', false, 7),
  ('Désinstallation — Décoration', 'Démonter les éléments de décoration', false, 1),
  ('Désinstallation — Décoration', 'Trier les éléments loués à rendre et les éléments achetés à conserver', false, 2),
  ('Désinstallation — Décoration', 'Emballer soigneusement les compositions florales à conserver si souhaité', false, 3),
  ('Désinstallation — Décoration', 'S’assurer que le lieu est remis dans son état initial : mobilier replacé, nappes retirées, etc.', false, 4),
  ('Désinstallation — Enveloppes & cadeaux', 'Inventorier le contenu de l’urne en présence de témoins : Jordan et/ou Sarah', false, 1),
  ('Désinstallation — Enveloppes & cadeaux', 'Lister les donateurs pour les remerciements personnalisés', false, 2),
  ('Désinstallation — Enveloppes & cadeaux', 'Remettre l’urne et les cadeaux physiques aux fiancés de façon sécurisée', false, 3),
  ('Désinstallation — Tâches génériques du lendemain', 'Faire l’état des lieux de sortie avec le propriétaire du lieu', false, 1),
  ('Désinstallation — Tâches génériques du lendemain', 'Vérifier les conditions de restitution du dépôt de garantie', false, 2),
  ('Désinstallation — Tâches génériques du lendemain', 'Prévoir des sacs poubelle pour le tri final des déchets si non géré la nuit précédente', false, 3),
  ('Désinstallation — Tâches génériques du lendemain', 'S’assurer que tout le matériel loué est restitué ou organisé pour restitution rapide', false, 4),
  ('Désinstallation — Tâches génériques du lendemain', 'Être disponible pour accompagner les invités vers leur hébergement ou leur transport si besoin', false, 5),
  ('Désinstallation — Tâches génériques du lendemain', 'Vérifier que les invités venant de loin ont bien leur moyen de retour organisé', false, 6),
  ('Désinstallation — Tâches génériques du lendemain', 'S’assurer que les personnes âgées ont un transport retour sécurisé', false, 7),
  ('Désinstallation — Tâches génériques du lendemain', 'Retourner les éléments de location dans les délais contractuels : matériel lumière, glacières, utilitaire', false, 8),
  ('Désinstallation — Tâches génériques du lendemain', 'Vérifier qu’aucun élément loué ne manque ou n’est endommagé avant restitution', false, 9),
  ('Après — Remerciements', 'Envoyer le message de remerciement aux invités préparé en amont', false, 1),
  ('Après — Remerciements', 'Envoyer un message personnalisé aux prestataires qui ont contribué bénévolement : DJ Djahman, cousins logistique, référents', false, 2),
  ('Après — Remerciements', 'Remercier chaque donateur d’enveloppe nommément', false, 3),
  ('Après — Remerciements', 'Remercier les traiteurs et fournisseurs externes avec lesquels tout s’est bien passé', false, 4),
  ('Après — Clôture financière', 'Mettre à jour le tableau de suivi des dépenses avec les dernières dépenses du jour J et du lendemain', false, 1),
  ('Après — Clôture financière', 'Vérifier que tous les soldes ont bien été réglés', false, 2),
  ('Après — Clôture financière', 'Récupérer le dépôt de garantie de la salle si non encore restitué', false, 3),
  ('Après — Clôture financière', 'Clôturer la comptabilité complète et archiver tous les documents et justificatifs', false, 4),
  ('Après — Clôture financière', 'Archiver les contrats, devis et bons de prestation dans le dossier dédié', false, 5),
  ('Après — Matériel & logistique post-événement', 'Vérifier que tout le matériel loué a bien été restitué dans les délais', false, 1),
  ('Après — Matériel & logistique post-événement', 'Signaler tout dommage constaté sur du matériel loué', false, 2),
  ('Après — Matériel & logistique post-événement', 'Ranger et stocker le matériel acheté : marmite, boîtes, accessoires bar, etc.', false, 3),
  ('Après — Matériel & logistique post-événement', 'Décider de la destination du stock de boissons restant : conserver ou redistribuer', false, 4),
  ('Après — Photos & vidéos', 'Confirmer les délais de livraison des photos/vidéos avec le prestataire', false, 1),
  ('Après — Photos & vidéos', 'Partager un lien pour que les invités déposent leurs propres photos', false, 2),
  ('Après — Photos & vidéos', 'Récupérer et sauvegarder les photos du prestataire dès réception', false, 3),
  ('Après — Photos & vidéos', 'Partager une sélection de photos avec les familles et proches', false, 4),
  ('Après — Décoration & fleurs', 'Retourner les derniers éléments de location si pas encore fait', false, 1),
  ('Après — Décoration & fleurs', 'Décider du devenir des compositions florales : conserver, offrir, jeter', false, 2),
  ('Après — Retours prestataires', 'Laisser des avis Google ou plateformes pour les prestataires qui l’ont mérité', false, 1),
  ('Après — Retours prestataires', 'Garder les coordonnées des prestataires pour de futurs événements', false, 2),
  ('Après — Retours prestataires', 'Faire un debriefing informel avec le coordinateur général pour noter les points à améliorer', false, 3),
  ('Après — Debriefing général', 'Rassembler les retours des référents sur ce qui a bien fonctionné et ce qui aurait pu être mieux géré', false, 1),
  ('Après — Debriefing général', 'Documenter les imprévus rencontrés et les solutions appliquées', false, 2),
  ('Après — Debriefing général', 'Archiver le conducteur final annoté pour référence future', false, 3)
),
resolved as (
  select
    c.id as checklist_id,
    s.label,
    s.is_done,
    s.sort_order
  from seed s
  join public._20260725_checklists c
    on c.title = s.checklist_title
)
insert into public._20260725_checklist_items (
  checklist_id,
  label,
  is_done,
  sort_order
)
select
  r.checklist_id,
  r.label,
  r.is_done,
  r.sort_order
from resolved r
where not exists (
  select 1
  from public._20260725_checklist_items existing
  where existing.checklist_id = r.checklist_id
    and existing.label = r.label
);

commit;
